# @timeout 600
# Upload file
POST https://api.openai.com/v1/files
Authorization: Bearer {{openai_api_key}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="mail_history.html""

< /Users/arkad/iCloudDrive/Семья/AI/Vasilisa/gmail/Вся%20почта,%20включая%20_Спам_%20и%20_Корзину_.mbox
--WebAppBoundary
Content-Disposition: form-data; name="purpose"

assistants
--WebAppBoundary--

###

# Assign file to store
POST https://api.openai.com/v1/vector_stores/vs_682cb2c892a08191b7372ca7a904c638/files
Content-Type: application/json
Authorization: Bearer {{openai_api_key}}

{
  "file_id": "file-NhNdMB74BYBhvK15fuujGK"
}

###
###  Get store
GET https://api.openai.com/v1/vector_stores/vs_682cb2c892a08191b7372ca7a904c638
Content-Type: application/json
Authorization: Bearer {{openai_api_key}}

###
###  Create store
POST https://api.openai.com/v1/vector_stores
Content-Type: application/json
Authorization: Bearer {{openai_api_key}}

{
  "expires_after": {
    "anchor": "last_active_at",
    "days": 30
  },
  "name": "vasilisa47@gmail"
}

###